frase = ('Curso em video Python')

print(frase[::2])
print(frase)
print(frase[9])
print(frase[9:13])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(frase[9:3])

print(len(frase))
print(frase.count('o'))
print(frase.count('o',0,13))
print(frase.find('deo'))
print(frase.find('Android'))
print('Curso' in frase)

print(frase.split())
print('-'.join(frase))

print(frase)
frase = (frase.replace('Python', 'Android'))
print(frase)
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())

frase1 = ('  Aprenda python   ')
print(frase1)
print(frase1.strip())
print(frase1.rstrip())
print(frase1.lstrip())

